# Generated by Django 3.1.1 on 2020-10-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201012_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
